// This file is auto-generated by massdriver from your massdriver.yaml file.
// Any changes made directly to this file will be overwritten on the next build.
// To opt a variable out of regeneration, move it to another file (e.g. variables.tf).
variable "aws_authentication" {
  type = object({
    arn         = string
    external_id = optional(string)
  })
}
variable "brokers_per_zone" {
  type = number
}
variable "instance_type" {
  type = string
}
variable "kafka_version" {
  type = string
}
variable "logging_method" {
  type = string
}
variable "md_metadata" {
  type = object({
    default_tags = map(string)
    deployment = object({
      id = string
    })
    name_prefix = string
    observability = object({
      alarm_webhook_url = string
    })
    package = object({
      created_at             = string
      deployment_enqueued_at = string
      previous_status        = string
      updated_at             = string
    })
    target = object({
      contact_email = string
    })
  })
}
variable "volume_size" {
  type = number
}
variable "vpc" {
  type = object({
    infrastructure = object({
      arn  = string
      cidr = string
      internal_subnets = list(object({
        arn = string
      }))
      private_subnets = list(object({
        arn = string
      }))
      public_subnets = list(object({
        arn = string
      }))
    })
    specs = optional(object({
      aws = optional(object({
        region = optional(string)
      }))
    }))
  })
}
